name: Build
on: [push , workflow_dispatch]
jobs:
  runs-on: ubuntu-latest
  steps:
    
    build:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install devs
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
