name: Print Json
on: 
  workflow_dispatch:
  pull_request:
    types: ["opened", "reopened", "edited"]
jobs:
  print:
    runs-on: ubuntu:latest
    steps:
      - name: Print
        run: echo "$ {{ toJSON(github.event) }} "
